steps:
# Stap 1: Build de Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/scooters-app:$SHORT_SHA', '.']

# Stap 2: Push de Image naar Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/scooters-app:$SHORT_SHA']

# Stap 3: Deploy naar Kubernetes met Helm
- name: 'gcr.io/cloud-builders/helm'
  args: ['upgrade', '--install', '--wait', 'scooters-app-release', './charts/scooters-app', '--set', 'image=gcr.io/$PROJECT_ID/scooters-app:$SHORT_SHA', '--namespace', '$_NAMESPACE']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=scooter-app-p'

substitutions:
  _NAMESPACE: 'default'
