steps:
- name: 'docker/compose:1.29.2'
  args: ['up', '--build', '-d']
  env:
  - 'PROJECT_ID=$PROJECT_ID'

  # Stap 1: Bouw de Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA', '.']

  # Stap 2: Push de image naar Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA']

  # Stap 3: Deploy naar GKE met kubectl
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', './k8s/', '--namespace', '${_NAMESPACE}']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'

substitutions:
  _ZONE: 'us-central1'
  _CLUSTER: 'scooter-app-p'
  _NAMESPACE: 'default'
