name: Deploy to Staging

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials scooter-app-p --zone us-central1 --project ${{ secrets.GCP_PROJECT_ID }}
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/production/
        kubectl set image deployment/scooter-app scooter-app=gcr.io/${{ secrets.GCP_PROJECT_ID }}/scooter-app:${{ github.sha }} 
